# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ml_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Database'


  # Pods for ml_demo

end
